
-- Advanced Business Analysis

-- Top selling products
-- Query the top 10 products by total sales value
-- Challenge: Include product name, total quantity sold, and total sales value
SELECT TOP 10
	p.product_id,
	p.product_name,
	SUM(s.quantitY) AS total_quantity,
	SUM(s.price_per_unit * s.quantity) AS total_sales
FROM gold.fact_sales S
LEFT JOIN gold.dim_products p
ON s.product_id = p.product_id
GROUP BY
	p.product_name,
	p.product_id
ORDER BY total_sales DESC

-- Revenue by category
-- Calculate total revenue generated by each product category
-- Challenge: Include the percentage contribution of each category to the total revenue 
WITH category_sales AS(
SELECT
	*,
	SUM(total_sales) OVER() AS overall_sales
FROM(
	SELECT
		p.category_id,
		p.category_name,
		ROUND(SUM(s.price_per_unit * s.quantity), 2) total_sales
	FROM gold.fact_sales s
	LEFT JOIN gold.dim_products p
	ON s.product_id = p.product_id
	GROUP BY
		p.category_id,
		p.category_name)t
)

SELECT
	category_id,
	category_name,
	total_sales,
	CONCAT(ROUND((CAST(total_sales AS FLOAT) / NULLIF(overall_sales, 0)) * 100, 2), ' %') category_percent_contribution
FROM category_sales

-- Average order value
-- Compute the average order value for each customer
-- Challenge: Include only customers with more than 5 orders
SELECT
	*,
	ROUND(
	CAST(total_sales AS FLOAT) / NULLIF(total_orders, 0), 2) AOV
FROM
(
	SELECT
		SUM(s.quantity * s.price_per_unit) total_sales,
		c.customer_id,
		CONCAT(c.first_name, ' ', c.last_name) customer_name,
		COUNT(DISTINCT order_id) total_orders
	FROM gold.fact_sales s
	LEFT JOIN gold.dim_customers c
	ON s.customer_id = c.customer_id
	GROUP BY
		c.customer_id,
		CONCAT(c.first_name, ' ', c.last_name)
	HAVING COUNT(DISTINCT order_id) > 5
)t
ORDER BY AOV DESC

-- Monthly Sales Trend
-- Query monthly total sales over the past year 
-- Challenge: Display the sales trend, grouping by month, return current_month sale, last_month sale
WITH past_year AS(
	SELECT
		*,
		YEAR(order_date) year_date
	FROM gold.fact_sales
	WHERE YEAR(order_date) = 2024
),

sales_trend AS(
SELECT
	*,
	SUM(total_sales) OVER(ORDER BY current_month) sales_trend,
	LAG(total_sales) OVER(order by current_month) previous_month
FROM
(
SELECT
	SUM(price_per_unit * quantity) total_sales,
	MONTH(order_date) current_month
FROM past_year
GROUP BY
	MONTH(order_date)
)t
)

SELECT
	*,
	ROUND((total_sales - previous_month) / NULLIF((previous_month), 0) * 100, 2) AS growth_percent
FROM sales_trend


-- Customers with no purchases
-- Find customers who have resigstered but never placed an order
-- Challenge: List all customer details and the time since their registeration -- N.B:All customers placed orders
SELECT
	c.customer_id,
	c.first_name,
	c.last_name,
	s.order_date
FROM gold.dim_customers c
LEFT JOIN gold.fact_sales s
ON c.customer_id = s.customer_id
WHERE s.order_date IS NULL 

-- Best selling categories by state
-- Identify the best-selling product category for each state
-- Challenge: Include sales for that category within each state

SELECT
*
FROM
(
SELECT
	p.category_id,
	p.category_name,
	c.state,
	SUM(s.price_per_unit * s.quantity) total_sales,
	RANK() OVER(PARTITION BY p.category_name ORDER BY SUM(s.price_per_unit * s.quantity) DESC) ranking_state
FROM gold.fact_sales s
LEFT JOIN  gold.dim_products p
ON s.product_id = p.product_id
LEFT JOIN gold.dim_customers c
ON s.customer_id = c.customer_id
GROUP BY
	p.category_id,
	p.category_name,
	c.state
)t
WHERE ranking_state = 1

-- Customer lifetime value (AOV * PURCHASE FREQUENCY * LIFESPAN_MONTHS)
-- calculate the total value of orders placed by each customer over their life time 
-- Challenge: Rank customers based on their CLTV
WITH sales_metrics AS(
SELECT
	c.customer_id,
	CONCAT(c.first_name, ' ', c.last_name) customer_name,
	SUM(s.price_per_unit * s.quantity) total_sales,
	MIN(s.order_date) first_order,
	MAX(s.order_date) last_order,
	DATEDIFF(MONTH, MIN(s.order_date), MAX(s.order_date)) life_span,
	COUNT(s.order_id) total_orders
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
ON s.customer_id = c.customer_id
GROUP BY 
	c.customer_id,
	CONCAT(c.first_name, ' ', c.last_name)
),

customer_metrics AS(
SELECT
	customer_id,
	customer_name,
	life_span,
	CAST(total_sales AS FLOAT) / NULLIF(total_orders, 0) AS average_order_value,
	CAST(total_orders AS FLOAT)/ NULLIF(life_span, 0) AS purchase_frequency,
	total_sales
FROM sales_metrics
)

SELECT
	customer_id,
	customer_name,
	total_sales,
	average_order_value * purchase_frequency * life_span AS customer_lifetime_value
FROM customer_metrics
ORDER BY customer_lifetime_value DESC

-- Inventory stock alerts
-- Query products with stock levels below a certain threshold (e.g less than 20 units)
-- Challenge: Include last restock date and warehouse information

SELECT
	product_id,
	warehouse_id,
	product_name,
	stock AS current_stock,
	last_stock_date
FROM gold.dim_products
WHERE stock < 20

-- Shipping delays
-- Identify orders where the shipping date is later than 7 days after the order date
-- Challenge: Include the customer, order details and delivery provider

SELECT
	c.customer_id,
	c.first_name,
	sh.shipping_prov,
	s.order_date,
	sh.shipping_date,
	DATEDIFF(DAY, s.order_date, sh.shipping_date) days_between_order_and_shipping,
	COUNT(*) total_orders
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
ON s.customer_id = c.customer_id
LEFT JOIN gold.dim_shipping sh
ON s.order_id = sh.order_id
GROUP BY
	c.customer_id,
	c.first_name,
	sh.shipping_prov,
	s.order_date,
	sh.shipping_date,
	DATEDIFF(DAY, s.order_date, sh.shipping_date) 
HAVING
	DATEDIFF(DAY, s.order_date, sh.shipping_date) > 7 
	AND
	shipping_prov IS NOT NULL
ORDER BY days_between_order_and_shipping

-- Payment success rate ' All payments succeeded'
-- calculate the percentage of successul payments across all orders
-- Challenge: include breakdowns by payment status failed or pending 

SELECT * FROM gold.dim_payments
WHERE payment_status != 'Payment Succeeded'

-- Top performance sellers
-- Find the top 5 sellers based on the total sales value 
-- Challenge: Include both succeeded and failed orders, and display the percentage of successfull orders
WITH top_sellers AS(
SELECT
	*,
	COUNT(*) OVER() total_orders,
	COUNT(*) OVER(PARTITION BY payment_status) successful_orders_count
FROM
(
SELECT TOP 5
	se.seller_id,
	se.seller_name,
	SUM(s.price_per_unit * s.quantity) total_sales,
	pa.payment_status
FROM gold.fact_sales s
LEFT JOIN gold.dim_sellers se
ON s.seller_id = se.seller_id
LEFT JOIN gold.dim_payments pa
ON pa.order_id = s.order_id
GROUP BY
	se.seller_id,
	se.seller_name,
	pa.payment_status
ORDER BY total_sales DESC
)t
)

SELECT
	*,
	CONCAT(CAST(successful_orders_count AS FLOAT) / NULLIF(total_orders, 0) * 100, ' %') AS percentage_of_successfull_orders
FROM top_sellers

-- Product profit margin
-- Calculate the profit margin for each product (difference between prince and cost of goods sold)
-- Challenge: Rank products by their profit margin, showing highest to lowest 

SELECT
	category_name,
	product_name,
	stock,
	price,
	cogs,
	price - cogs AS profit_margin
FROM gold.dim_products
ORDER BY profit_margin DESC

-- Inactive sellers 'All sellers are active'
-- Identify the inactive sellers who have not made any sales in the last 6 months 
-- Challenge: show the last sale date and total sales from the sellers 
SELECT
	se.seller_id,
	se.seller_name,
	s.order_id
FROM gold.dim_sellers se
LEFT JOIN gold.fact_sales s
ON se.seller_id = s.seller_id
WHERE s.order_id IS NULL
	  AND s.order_id NOT IN (
	  SELECT
		order_id
	  FROM gold.fact_sales
	  WHERE order_date >= DATEADD(MONTH, -6, GETDATE()))

-- categorize customers into returning or new
-- if the customer has done more than 5 returns categorize them as returning customers else new
-- Challenge: List all customers id, name, total orders, total returns 
WITH customers_info AS(
SELECT
	s.customer_id,
	CONCAT(c.first_name, ' ', c.last_name) customer_name,
	COUNT(DISTINCT s.order_id) total_orders,
	COUNT(sh.return_date) total_returns
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
ON s.customer_id = c.customer_id
LEFT JOIN gold.dim_shipping sh
ON s.order_id = sh.order_id
GROUP BY 
	s.customer_id,
	CONCAT(C.first_name, ' ', last_name)
)

SELECT
	*,
	CASE
		WHEN total_returns > 5 THEN 'High risk customer'
		ELSE 'New'
	End customer_categorization
FROM customers_info

-- Top 5 customers by orders in each state
-- Identify the top 5 customers with the highest number of orders for each state 
-- Challenge: Include the number of orders and total sales for each customer
WITH customers_ranking AS(
SELECT
	c.customer_id,
	c.state,
	COUNT(DISTINCT order_id) total_orders,
	SUM(s.price_per_unit * s.quantity) total_sales,
	DENSE_RANK() OVER(PARTITION BY c.state ORDER BY COUNT(DISTINCT order_id) DESC) rank_per_state
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
ON s.customer_id = c.customer_id
GROUP BY c.customer_id,
		 c.state
)

SELECT
	*
FROM customers_ranking
WHERE rank_per_state <= 5

-- Revenue by shipping provirder
-- Calculate the total revenue handled by each shipping provider
-- Challenge: Include the total number of orders and the average delivery time for each provider

WITH shipping_info AS (
SELECT
	sh.shipping_prov,
	SUM(s.price_per_unit * s.quantity) total_sales,
	s.order_date,
	sh.shipping_date AS delivery_date,
	DATEDIFF(DAY, s.order_date, sh.shipping_date) delivery_time
FROM gold.fact_sales s
LEFT JOIN gold.dim_shipping sh
ON s.order_id = sh.order_id
WHERE shipping_prov IS NOT NULL AND s.order_date < sh.shipping_date
GROUP BY 
	sh.shipping_prov,
	s.order_date,
	sh.shipping_date
)

SELECT
	*,
	CAST(total_days AS FLOAT) / NULLIF(total_nr_days, 0) average_Delivery_time
FROM
(
SELECT
	*,
	SUM(delivery_time) OVER(PARTITION BY shipping_prov) total_days,
	COUNT(delivery_time) OVER(PARTITION BY shipping_prov) total_nr_days
FROM shipping_info
)t

-- TOP 10 products with highest decreasing revenue ratio compare to the last year 2023 and current year 2024
-- Challenge: Reutrn product_id, product_name, category_name, 2022 and 2023 revenue decrease ratio at end ROUND the result
-- Note: Decrease Ratio = cr - ls / ls * 100 (cs = current year ls = last year)

WITH product_sales_year_by_year AS(
SELECT
	p.product_id,
	p.product_name,
	p.category_name,
	SUM(CASE WHEN YEAR(s.order_date) = 2024 THEN (s.price_per_unit * s.quantity) ELSE 0 END) AS revenue_2024,
	SUM(CASE WHEN YEAR(s.order_date) = 2023 THEN (s.price_per_unit * s.quantity) ELSE 0 END) AS reveneu_2023
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p
ON s.product_id = p.product_id
GROUP BY 
	p.product_id,
	p.product_name,
	p.category_name
)

SELECT TOP 10
	product_id,
	product_name,
	category_name,
	revenue_2024,
	reveneu_2023,
	ROUND(CAST((revenue_2024 - reveneu_2023) AS FLOAT ) / NULLIF(reveneu_2023, 0), 2) AS decrease_ratio
FROM product_sales_year_by_year
WHERE revenue_2024 < reveneu_2023 and revenue_2024 > 0
ORDER BY decrease_ratio 


